config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :cars do
        resources :car_statuses do
          resources :car_images
        end
      end
    end

  root 'users#index'

end

app/controllers/car_statuses_controller.rb
# == Schema Information
#
# Table name: car_statuses
#
#  id          :integer          not null, primary key
#  description :text
#  status      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  car_id      :integer
#

class CarStatusesController < ApplicationController
  before_action :set_car_status, only: [:show, :edit, :update, :destroy]
  before_action :set_car
  before_action :set_user

  # GET /car_statuses
  # GET /car_statuses.json
  def index
    @car_statuses = CarStatus.all
    @car_images = CarImage.all
    @users = User.all
  end

  # GET /car_statuses/1
  # GET /car_statuses/1.json
  def show
    @car_images = CarImage.where(car_status_id: @car_status.id)
  end

  # GET /car_statuses/new
  def new
    @car_status = CarStatus.new
  end

  # GET /car_statuses/1/edit
  def edit
  end

  # POST /car_statuses
  # POST /car_statuses.json
  def create
    @car_status = CarStatus.new(car_status_params)
    @car_status.car_id = @car.id
    if @car_status.save
        redirect_to user_car_path(@user,@car), notice: 'Car was successfully created.'
      else
        render 'new'

      end
    end


  # PATCH/PUT /car_statuses/1
  # PATCH/PUT /car_statuses/1.json
  def update
    respond_to do |format|
      if @car_status.update(car_status_params)
        format.html { redirect_to user_car_path(@user,@car), notice: 'Car status was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: user_car_path(@user,@car).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_statuses/1
  # DELETE /car_statuses/1.json
  def destroy
    @car_status.destroy
    respond_to do |format|
      format.html { redirect_to user_car_path(@user,@car,@car_status), notice: 'Car Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_status
      @car_status = CarStatus.find(params[:id])
    end

    def set_car
      @car = Car.find(params[:car_id])

    end

    def set_user
      @user = User.find(params[:user_id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_status_params
      params.require(:car_status).permit(:description, :status)
    end
end

app/helpers/car_statuses_helper.rb
# == Schema Information
#
# Table name: car_statuses
#
#  id          :integer          not null, primary key
#  description :text
#  status      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  car_id      :integer
#

module CarStatusesHelper
end

app/views/car_statuses/_adminshow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>Car Statuss</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">Description</th>
        <th class="text-center">Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
        <% if @car_status.status == true %>
          <tr class="success">
            <td><%= @car_status.description %></td>
            <td><button type="button" class="btn btn-success btn-sm active" disabled="disabled"><i class="fa fa-check"></i></button></td>

        <%else%>
          <tr class="danger">
            <td><%= @car_status.description %></td>
            <td><button type="button" class="btn btn-danger btn-sm active" disabled="disabled"><i class="fa fa-times"></i></button></td>

        <%end%>




        <td><%= link_to 'Edit Status', edit_user_car_car_status_path, class: "btn btn-primary" %></td>
      </tr>
    </tbody>
  </table>
</div>





  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Car Image</h4></td>
    </div>
  <%if @car_images.blank? %>
    <div class="container">
      <h3>No Image Yet, Would yo like to add it first?</h3>
      <%= link_to 'Add Photo', new_user_car_car_status_car_image_path(@user,@car,@car_status), class: "btn btn-danger" %><br><br>
    </div>

  <%else%>
    <% i = 1 %>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">Lists</th>
          <th class="text-center">Details</th>
          <th class="text-center">Images</th>
          <th colspan="2"></th>
        </thead>
        <tbody>
          <% @car_images.each do |car_image| %>
            <tr>
              <td><%= i %></td>
              <td><%= car_image.image_name %></td>
              <td><%= image_tag car_image.image.url(:thumb) %></td>
              <td><%= link_to 'Edit Image', edit_user_car_car_status_car_image_path(@user,@car,@car_status, car_image), class: "btn btn-primary" %></td>
              <td><%= link_to 'Destroy', user_car_car_status_car_image_path(@user,@car,@car_status, car_image), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>


            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>

</div>

<%= link_to 'Add Photo', new_user_car_car_status_car_image_path(@user,@car,@car_status), class: "btn btn-primary" %>



<%= link_to 'Edit Status', edit_user_car_car_status_path, class: "btn btn-primary" %>
<%= link_to 'Back', user_car_path(@user,@car), class: "btn btn-primary"  %>
<br><br>

app/views/car_statuses/_form.html.erb
<%= form_for [@user,@car,@car_status], html: { multipart: true } do |f| %>
  <% if @car_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_status.errors.count, "error") %> prohibited this car_status from being saved:</h2>

      <ul>
      <% @car_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>






  <form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2"><%= f.label :description %> :</label>
    <div class="col-sm-7">
      <%= f.text_area :description,class:"description_carstatus form-control", rows:"1" %>
    </div>
  </div><br><br>

  <div class="form-group">
    <label class="col-sm-2"><%= f.label :status %> :</label>
    <div class="col-sm-9">
      <%= f.check_box :status %>
    </div>
  </div><br><br>





  <div class="actions btn">
    <%= f.submit%>
  </div><br><br>

  </form>


<% end %>

app/views/car_statuses/_usershow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>Car Statuss</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">Description</th>
        <th class="text-center">Status</th>
      </tr>
    </thead>

    <tbody>
        <% if @car_status.status == true %>
          <tr class="success">
            <td><%= @car_status.description %></td>
            <td><button type="button" class="btn btn-success btn-sm active" disabled="disabled"><i class="fa fa-check"></i></button></td>

        <%else%>
          <tr class="danger">
            <td><%= @car_status.description %></td>
            <td><button type="button" class="btn btn-danger btn-sm active" disabled="disabled"><i class="fa fa-times"></i></button></td>

        <%end%>




      </tr>
    </tbody>
  </table>
</div>





  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Car Image</h4></td>
    </div>
  <%if @car_images.blank? %>
    <div class="container">
      <h3>No Image Yet, Please Contact Us</h3>
    </div>

  <%else%>
    <% i = 1 %>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">Lists</th>
          <th class="text-center">Details</th>
          <th class="text-center">Images</th>
        </thead>
        <tbody>
          <% @car_images.each do |car_image| %>
            <tr>
              <td><%= i %></td>
              <td><%= car_image.image_name %></td>
              <td><%= image_tag car_image.image.url(:thumb) %></td>


            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>

</div>




<%= link_to 'Back', user_car_path(@user,@car), class: "btn btn-primary"  %>
<br><br>

app/views/car_statuses/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>Editing Car Status</h1>
  </div>

  <br>
  <div class="container">
    <%= render 'form' %>
  </div>

</div>
<%= link_to 'Back', user_car_car_status_path(@user,@car,@car_status), class: "btn btn-primary" %>

app/views/car_statuses/index.html.erb
<h1>Listing Car Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_statuses.each do |car_status| %>
      <tr>
        <td><%= car_status.description %></td>
        <td><%= car_status.status %></td>
        <td><%= link_to 'Show', car_status %></td>
        <td><%= link_to 'Edit', edit_car_status_path(car_status) %></td>
        <td><%= link_to 'Destroy', car_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car status', new_car_status_path %>

app/views/car_statuses/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>New Car Status</h1>
  </div>

  <br>
  <div class="container">
    <!-- <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineCheckbox1" value="เตรียมพร้อม"> เตรียมพร้อม
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineCheckbox2" value="รื้อ"> รื้อ
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineCheckbox3" value="พ่นสี"> พ่นสี
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineCheckbox1" value="ประกอบ"> ประกอบ
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineCheckbox2" value="ขัดสี"> ขัดสี
    </label>

    <br><br> -->




    <%= render 'form' %>
    <!-- <div class="checkboxselect">

    </div> -->
  </div>

</div>
<%= link_to 'Back', user_car_path(@user,@car), class: "btn btn-primary" %>









<!-- <script type="text/javascript">
var keep_value = "";
$(".description_carstatus").html("");
$('.radio-inline :radio').click(function() {
  $("textarea").html("");
  var $this = $(this);
  // $this will contain a reference to the checkbox
  var xx = this.value
  // console.log("this.value",xx);
  // console.log("keep_value1",keep_value);
  var x = "#"+this.value
  // console.log(xx);
  // console.log(x);
  if ($this.is(':checked')) {
    // console.log("keep_value2",keep_value);
    if (keep_value != xx) {
      $(".description_carstatus").html("");
    }else {
      $(".description_carstatus").html("");
    }
      keep_value = xx
      $('.description_carstatus').append(xx)
      // console.log("keep_value3",keep_value);

  }else {
    $(".description_carstatus").html("");
  }

  // console.log(keep_status);
  // console.log("keep_value4",keep_value);
});
$(".description_carstatus").html("");

</script> -->