config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :cars do
        resources :car_statuses do
          resources :car_images
        end
      end
    end

  root 'users#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  gender          :text
#  birth_date      :date
#  email           :string
#  mobile_number   :text
#  password        :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class User < ActiveRecord::Base
  validates :first_name, :last_name,:mobile_number, presence: true
  has_many :cars, dependent: :destroy



  has_secure_password
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  gender          :text
#  birth_date      :date
#  email           :string
#  mobile_number   :text
#  password        :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @cars = Car.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @cars = Car.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :gender, :birth_date, :email, :mobile_number, :password)
    end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  gender          :text
#  birth_date      :date
#  email           :string
#  mobile_number   :text
#  password        :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

module UsersHelper
end

app/views/users/_adminindex.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>Listing Users</h1>
  </div>

  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">First name</th>
        <th class="text-center">Last name</th>
        <th class="text-center">Gender</th>
        <th class="text-center">Birth date</th>
        <th class="text-center">Email</th>
        <th class="text-center">Mobile number</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.gender %></td>
          <td><%= user.birth_date %></td>
          <td><%= user.email %></td>
          <td><%= user.mobile_number %></td>
          <td><%= link_to 'Show', user ,class: "btn btn-primary"%></td>
          <td><%= link_to 'Edit', edit_user_path(user),class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>

  <%= link_to 'New User', new_user_path,class: "btn btn-primary" %>

app/views/users/_adminshow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>User Informations</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">First Name</th>
        <th class="text-center">Last Name</th>
        <th class="text-center">Gender</th>
        <th class="text-center">Birth Date</th>
        <th class="text-center">Email</th>
        <th class="text-center">Mobile Number</th>
        <th class="text-center">Password</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @user.first_name %></td>
        <td><%= @user.last_name %></td>
        <td><%= @user.gender %></td>
        <td><%= @user.birth_date %></td>
        <td><%= @user.email %></td>
        <td><%= @user.mobile_number %></td>
        <td><%= @user.password %></td>
      </tr>
    </tbody>
  </table>
</div>




  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Cars</h4></td>
    </div>
  <%if @cars.blank? %>
  <div class="container">
    <h3>No Car Yet, Would yo like to add it first?</h3>
    <%= link_to 'Add car', new_user_car_path(@user), class: "btn btn-danger" %><br><br>
  </div>
  <%else%>
    <% i = 1 %>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">Car license</th>
          <th class="text-center">Description</th>
          <th class="text-center">Enter date</th>
          <th class="text-center">Car category</th>
          <th class="text-center">Car subcategory</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @cars.each do |car| %>
          <tr>
            <td><%= car.car_license %></td>
            <td><%= car.description %></td>
            <td><%= car.enter_date %></td>
            <td><%= car.car_category %></td>
            <td><%= car.car_subcategory %></td>
            <td><%= link_to 'Status', user_car_path(@user,car), class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit Car', edit_user_car_path(@user, car), class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', user_car_path(@user, car), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>


            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>


</div>

<br><br>


<%= link_to 'Add Car', new_user_car_path(@user), class: "btn btn-primary" %>
<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
<%= link_to 'Back', users_path, class: "btn btn-primary" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :first_name%> :</label>
      <div class="col-sm-9">
        <%= f.text_field :first_name,class:"form-control"%>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :last_name%> :</label>
      <div class="col-sm-9">
        <%= f.text_field :last_name,class:"form-control"%>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :gender%> :</label>
      <div class="col-sm-9">

      <select class="form-control" type="text" name="user[gender]" id="user_gender">
        <option>male</option>
        <option>female</option>

      </select>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :birth_date%> :</label>
      <div class="col-sm-9">
        <%= f.date_select :birth_date,class:"form-control",:start_year => Time.now.year - 100, :end_year => Time.now.year%>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :email%> :</label>
      <div class="col-sm-9">
        <%= f.text_field :email,class:"form-control"%>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :mobile_number%> :</label>
      <div class="col-sm-9">
        <%= f.text_field :mobile_number,class:"form-control"%>
      </div>
    </div><br><br><br>
    <div class="form-group">
      <label class="col-sm-2"><%= f.label :password ,placeholder: "Password"%> :</label>
      <div class="col-sm-9">
        <%= f.text_field :password,class:"form-control"%>
      </div>
    </div><br><br><br>

    <div class="actions">
      <%= f.submit %>
    </div>
  </form>
<% end %>

app/views/users/_userindex.html.erb
<h1>Listing Users</h1>

<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </tfoot>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.gender %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
          Show
        </button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>






<!-- Modal -->
<form class="" action="<%= users_path %>" method="post" onsubmit="postAnswer()">

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please Enter the Password:</h4>
      </div>

      <div class="modal-body"><br>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
          <div class="col-sm-10">
            <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
          </div>
        </div><br>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Enter</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

      </div>
      <%= hidden_field_tag "password_info" %>
    </div>
  </div>
</div>
</form>





<% content_for :js do %>
<script>
  function postAnswer(){
    var password_info = "<%= params[:password] %>";
    $("#password_info").val(password_info);
  }


</script>



<% end %>

app/views/users/_usershow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>User Informations</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">First Name</th>
        <th class="text-center">Last Name</th>
        <th class="text-center">Gender</th>
        <th class="text-center">Birth Date</th>
        <th class="text-center">Email</th>
        <!-- <th class="text-center">Mobile Number</th> -->
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @user.first_name %></td>
        <td><%= @user.last_name %></td>
        <td><%= @user.gender %></td>
        <td><%= @user.birth_date %></td>
        <td><%= @user.email %></td>
        <!-- <td><%= @user.mobile_number %></td> -->
      </tr>
    </tbody>
  </table>
</div>




  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Cars</h4></td>
    </div>
  <%if @cars.blank? %>
  <div class="container">
    <h3>No Car Yet, Please Contact Us.</h3>
  </div>
  <%else%>
    <% i = 1 %>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">Car license</th>
          <th class="text-center">Description</th>
          <th class="text-center">Enter date</th>
          <th class="text-center">Car category</th>
          <th class="text-center">Car subcategory</th>
          <th></th>
        </thead>
        <tbody>
          <% @cars.each do |car| %>
          <tr>
            <td><%= car.car_license %></td>
            <td><%= car.description %></td>
            <td><%= car.enter_date %></td>
            <td><%= car.car_category %></td>
            <td><%= car.car_subcategory %></td>
            <td><%= link_to 'Status', user_car_path(@user,car), class: "btn btn-primary" %></td>



            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>


</div>

<br><br>


<%= link_to 'Back', users_path, class: "btn btn-primary" %>

app/views/users/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>Editing User</h1>
  </div>

  <br>
  <div class="container">
    <%= render 'form' %><br><br>
  </div>

</div>
<%= link_to 'Back', user_path(@user), class: "btn btn-primary" %>

app/views/users/index.html.erb
<% if admin_signed_in? %>
  <%= render 'adminindex'%>
<% else %>
  <%= render 'userindex'%>
<% end %>

app/views/users/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">

    <h1>New User</h1>
  </div>
  <div class="container">
    <%= render 'form' %>
    <br><br>
  </div>
</div>

<%= link_to 'Back', users_path  , class: "btn btn-primary" %>

app/views/users/show.html.erb
<% if admin_signed_in? %>
  <%= render 'adminshow'%>
<% else %>
  <%= render 'usershow'%>
<% end %>