config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :cars do
        resources :car_statuses do
          resources :car_images
        end
      end
    end

  root 'users#index'

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id              :integer          not null, primary key
#  car_license     :string
#  description     :text
#  enter_date      :date
#  car_category    :string
#  car_subcategory :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

class Car < ActiveRecord::Base
  validates :car_license, presence: true
  belongs_to :user
  has_many :car_statuses, dependent: :destroy
  # def status_percent_calculate(status=true)
  #   all = self.car_statuses.count
  #   done = self.car_statuses.where(status: status).count
  #   (done/all).to_f
  # end
end

app/controllers/cars_controller.rb
# == Schema Information
#
# Table name: cars
#
#  id              :integer          not null, primary key
#  car_license     :string
#  description     :text
#  enter_date      :date
#  car_category    :string
#  car_subcategory :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_user


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @car_statuses = CarStatus.all
    @users = User.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @cars = Car.all
    @car_images = CarImage.all
    @car_statuses = CarStatus.where(car_id: @car.id)
    @users = User.all
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    checkbox = params[:inlineCheckboxhidden].split(",")

    @car = Car.new(car_params)
    @car.user_id = @user.id

    respond_to do |format|
      if @car.save
        checkbox.each do |c|
          @car_status = CarStatus.create(description: c, status: false, car_id: @car.id)
          @car_status.save
        end
        format.html { redirect_to user_car_path(@user,@car), notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: user_car_path(@user,@car).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @user, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end
    def set_user
      @user = User.find(params[:user_id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_license, :description, :enter_date, :car_category, :car_subcategory)
    end
end

app/helpers/cars_helper.rb
# == Schema Information
#
# Table name: cars
#
#  id              :integer          not null, primary key
#  car_license     :string
#  description     :text
#  enter_date      :date
#  car_category    :string
#  car_subcategory :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

module CarsHelper
end

app/views/cars/_adminindex.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>Listing Cars</h1>
  </div>

<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th class="text-center">Car license</th>
      <th class="text-center">Description</th>
      <th class="text-center">Enter date</th>
      <th class="text-center">Car category</th>
      <th class="text-center">Car subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.car_license %></td>
        <td><%= car.description %></td>
        <td><%= car.enter_date %></td>
        <td><%= car.car_category %></td>
        <td><%= car.car_subcategory %></td>
        <td><%= link_to 'Add Status', new_user_car_car_status(@user,car),class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_car_path(car),class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'New Car', new_car_path,class: "btn btn-primary" %>

app/views/cars/_adminshow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>Car Informations</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">Car license</th>
        <th class="text-center">Description</th>
        <th class="text-center">Enter date</th>
        <th class="text-center">Car category</th>
        <th class="text-center">Car subcategory</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @car.car_license %></td>
        <td><%= @car.description %></td>
        <td><%= @car.enter_date %></td>
        <td><%= @car.car_category %></td>
        <td><%= @car.car_subcategory %></td>
      </tr>
    </tbody>
  </table>
</div>



<div class="progress">
</div>







  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Car Status</h4></td>
    </div>
  <%if @car_statuses.blank? %>
  <div class="container">
    <h3>No Car Status Yet, Would yo like to add it first?</h3>
    <%= link_to 'Add Status', new_user_car_car_status_path(@user,@car), class: "btn btn-danger" %><br><br>
  </div>
  <%else%>
    <% i = 1 %>
    <% keep_status = []%>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">List</th>
          <th class="text-center">Order</th>
          <th class="text-center">Status</th>
          <th class="text-center">Image</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @car_statuses.each do |car_status| %>
          <% keep_status.push(car_status.status)%>
            <% if car_status.status == false %>
            <tr class="danger">
              <td><%= i %></td>
              <td><%= car_status.description %></td>
              <td><button type="button" class="btn btn-danger btn-sm active" disabled="disabled"><i class="fa fa-times"></i></button></td>

            <%else%>
            <tr class="success">
              <td><%= i %></td>
              <td><%= car_status.description %></td>
              <td><button type="button" class="btn btn-success btn-sm active" disabled="disabled"><i class="fa fa-check"></i></button></td>


            <%end %>


              <td>Image</td>
              <td><%= link_to 'Image', user_car_car_status_path(@user,@car,car_status), class: "btn btn-primary" %></td>
              <td><%= link_to 'Edit Status', edit_user_car_car_status_path(@user,@car, car_status), class: "btn btn-primary" %></td>
              <td><%= link_to 'Destroy', user_car_car_status_path(@user,@car, car_status), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>


            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>


</div>

<br><br>
<%= link_to 'Add Status', new_user_car_car_status_path(@user,@car), class: "btn btn-primary" %>
<%= link_to 'Edit Car', edit_user_car_path(@user,@car), class: "btn btn-primary" %>
<%= link_to 'Back', user_path(@user), class: "btn btn-primary" %>













<script type="text/javascript">
// console.log("i = ",typeof(<%=i %>));
var keep_num_true = 0;
var keep_num_false = 0;
var check = 100;

var xxxx= 0;
// console.log("xxxxxx", typeof(xxxx));
var status = <%=keep_status%>
var array = status.split(',');
var keep_num = array.length
// console.log(status);
// console.log(typeof(status));
// console.log("status length", status.length);
// console.log(array[0]);
// console.log(typeof(array[0]));
// console.log("arra length", array.length);
for (var num = 0; num < array.length; num++) {
  // console.log("array[num]",array[num]);
  if (array[num] == 'true') {
    // console.log("true--------------");
    // console.log("aaaa",num);
    keep_num_true += 1;
    // console.log("keep_num_true", keep_num_true);
  }else {
    keep_num_false += 1;
  }
}
// console.log("num",keep_num);
// console.log("num",typeof(keep_num));
// console.log("true",keep_num_true);
// console.log("true",typeof(keep_num_true));
// console.log("false",keep_num_false);
// console.log("false",typeof(keep_num_false));
  if (keep_num_true == 0) {

    var find_percent = 0;
  }else {
    // console.log("keep_num_true / keep_num * 100",(keep_num_true / keep_num));
    var find_percent = (keep_num_true / keep_num) * check;
  }
  var t1 = "<div class='progress-bar progress-bar-info' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"%'"+ ">"+"<span class='sr-only'>"+find_percent + "%"+ "Complete</span>"+find_percent + "%"+"</div>";
  // console.log("<div class='progress-bar' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"'"+ ">"+find_percent + "%"+"</div>");
  // console.log(t1);
  $('.progress').append("<div class='progress-bar progress-bar-info progress-bar-striped' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"%'"+ ">"+"<span class='sr-only'>"+find_percent + "%"+ "Complete</span>"+find_percent + "%"+"</div>")
  keep_num = 0;
  keep_num_true = 0;
  keep_num_false = 0;
  find_percent = 0;
</script>

app/views/cars/_form.html.erb
<%= form_for [@user,@car], html: { multipart: true } do |f| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<form class="form-horizontal">
<div class="form-group">
  <label class="col-sm-2"><%= f.label :car_license%> :</label>
  <div class="col-sm-9">
    <%= f.text_field :car_license ,class:"form-control"%>
  </div>
</div><br><br><br>

<div class="form-group">
  <label class="col-sm-2"><%= f.label :description %> :</label>
  <div class="col-sm-9">
    <%= f.text_area :description,class:"form-control", rows:"1" %>
  </div>
</div><br><br>

<div class="form-group">
  <label class="col-sm-2"><%= f.label :car_category %> :</label>
  <div class="col-sm-9">
    <%= f.text_field :car_category,class:"form-control" %>
  </div>
</div><br><br>
<div class="form-group">
  <label class="col-sm-2"><%= f.label :car_subcategory %> :</label>
  <div class="col-sm-9">
    <%= f.text_field :car_subcategory,class:"form-control" %>
  </div>
</div><br><br>
<div class="form-group">
  <label class="col-sm-2"><%= f.label :enter_date %> :</label>
  <div class="col-sm-9">
    <%= f.date_select :enter_date %>
  </div>
</div><br><br>
<div class="form-group">
  <label class="col-sm-2">Status :</label>
  <div class="col-sm-9" id="checkboxdiv">
    <label class="checkbox-inline" id="labelid">
      <input class = "inputcheckbox"type="checkbox" id="inlineCheckbox" value="เตรียมพร้อม" data-toggle="tooltip" data-placement="top" title="Tooltip on top"> เตรียมพร้อม
    </label>
    <label class="checkbox-inline" id="labelid">
      <input class = "inputcheckbox"type="checkbox" id="inlineCheckbox" value="รื้อ"> รื้อ
    </label>
    <label class="checkbox-inline" id="labelid">
      <input class = "inputcheckbox"type="checkbox" id="inlineCheckbox" value="พ่นสี"> พ่นสี
    </label>
    <label class="checkbox-inline" id="labelid">
      <input class = "inputcheckbox"type="checkbox" id="inlineCheckbox" value="ประกอบ"> ประกอบ
    </label>
    <label class="checkbox-inline" id="labelid">
      <input class = "inputcheckbox"type="checkbox" id="inlineCheckbox" value="ขัดสี"> ขัดสี
    </label>
  </div>
</div><br>


<div class="">
  <div class="checkboxselect">

  </div><br><br>
</div>


<%= hidden_field_tag "inlineCheckboxhidden" %>


<div class="actions btn">
  <%= f.submit%>
</div><br><br>

</form>



<% end %>

















<script type="text/javascript">

var keep_status = [];
var keep_status_hidden = [];
$('.checkbox-inline :checkbox').click(function() {

var $this = $(this);
// $this will contain a reference to the checkbox
var xx = this.value
// console.log(typeof(xx));
// console.log(xx);

var x = "#"+this.value
if ($this.is(':checked')) {
    // console.log("11111");
    // console.log(this.value);
    keep_status.push(this.value);
    $('.checkboxselect').append("<p id='"+xx+"'> &#0149; " +this.value+"</p>")
    $('#inlineCheckbox').append(xx)
    // console.log(keep_status);

    // console.log($this);
    // $('.checkboxselect').append("<p>"+this.value+"</p>")
} else {
  // console.log("222222");
  for (var i = 0; i < keep_status.length; i++) {
    // console.log("kkk",keep_status[i]);
    if (keep_status[i] == this.value) {
      // console.log("i =", i);
      // console.log("keep_status[i]",keep_status[i]);
      // console.log("this.value = ",this.value);
      // keep_status.remove(keep_status.i)
      delete keep_status[i];
      $(x).remove();


      // $('p').remove("'"+x+"'");

    }
  }
  // console.log("keep_status_hidden 222 =",keep_status_hidden);


}
$('#inlineCheckboxhidden').val("");

keep_status_hidden =[]
// console.log(keep_status);
// console.log("------------------------------before loop------------------------------");
for (var i = 0; i < keep_status.length; i++) {
  // console.log("keep_status[i]",keep_status[i]);
  if (i==0) {
    if (keep_status[i] != undefined) {
      keep_status_hidden += keep_status[i]
    }

  }else {
    if (keep_status[i] != undefined) {
      keep_status_hidden += ","+keep_status[i]
    }
  }
}
// }console.log("keep_status_hidden 0 =",keep_status_hidden[0]);
if (keep_status_hidden[0] == ','){
  keep_status_hidden = keep_status_hidden.substring(1);
  // console.log("keep_status_hidden --- =",keep_status_hidden);
}

// keep_status_hidden=[]


// keep_status_hidden += keep_status.toString()
// console.log("keep_status.toString() = ",keep_status.toString());

// console.log($('#inlineCheckbox').value);
// keep_status_hidden=[]
// for (var i = 0; i < keep_status.length; i++) {
//   console.log("keep_status[i] = ",keep_status[i]);
//   if (keep_status[i] != "undefined") {
//     keep_status_hidden += keep_status[i]
//
//   }
//
//



  // if (i==0) {
  //   keep_status_hidden += keep_status[i]
  // }else{
  //   if (keep_status[i]!= "undefined") {
  //     console.log("aaa");
  //     keep_status_hidden += ","+keep_status[i]
  //   }
  // }

// }
// console.log("keep_status_hidden 111 =",keep_status_hidden);
$('#inlineCheckboxhidden').val(keep_status_hidden);
});







</script>

app/views/cars/_userindex.html.erb
<h1>List of Cars</h1>



<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Car license</th>
      <th>Description</th>
      <th>Enter date</th>
      <th>Car category</th>
      <th>Car subcategory</th>
      <th></th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Car license</th>
      <th>Description</th>
      <th>Enter date</th>
      <th>Car category</th>
      <th>Car subcategory</th>
      <th></th>
    </tr>
  </tfoot>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.car_license %></td>
        <td><%= car.description %></td>
        <td><%= car.enter_date.to_formatted_s(:long_ordinal) %></td>
        <td><%= car.car_category %></td>
        <td><%= car.car_subcategory %></td>
        <td><%= link_to 'Show', car %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/_usershow.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <td><h4>Car Informations</h4></td>
  </div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th class="text-center">Car license</th>
        <th class="text-center">Description</th>
        <th class="text-center">Enter date</th>
        <th class="text-center">Car category</th>
        <th class="text-center">Car subcategory</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @car.car_license %></td>
        <td><%= @car.description %></td>
        <td><%= @car.enter_date %></td>
        <td><%= @car.car_category %></td>
        <td><%= @car.car_subcategory %></td>
      </tr>
    </tbody>
  </table>
</div>



<div class="progress">
</div>







  <div class="panel panel-primary">
    <div class="panel-heading panel-primary">
      <td><h4>Car Status</h4></td>
    </div>
  <%if @car_statuses.blank? %>
  <div class="container">
    <h3>No Car Status Yet, Please Contact Us?</h3>
  </div>
  <%else%>
    <% i = 1 %>
    <% keep_status = []%>
      <table class="table table-bordered text-center">
        <thead>
          <th class="text-center">List</th>
          <th class="text-center">Order</th>
          <th class="text-center">Status</th>
          <th class="text-center">Image</th>
          <th ></th>
        </thead>
        <tbody>
          <% @car_statuses.each do |car_status| %>
          <% keep_status.push(car_status.status)%>
            <% if car_status.status == false %>
            <tr class="danger">
              <td><%= i %></td>
              <td><%= car_status.description %></td>
              <td><button type="button" class="btn btn-danger btn-sm active" disabled="disabled"><i class="fa fa-times"></i></button></td>

            <%else%>
            <tr class="success">
              <td><%= i %></td>
              <td><%= car_status.description %></td>
              <td><button type="button" class="btn btn-success btn-sm active" disabled="disabled"><i class="fa fa-check"></i></button></td>


            <%end %>


              <td>Image</td>
              <td><%= link_to 'Image', user_car_car_status_path(@user,@car,car_status), class: "btn btn-primary" %></td>



            </tr>

            <% i = i+1 %>
        </tbody>


  <%end %>
  <%end %>
    </table>


</div>

<br><br>

<%= link_to 'Back', user_path(@user), class: "btn btn-primary" %>













<script type="text/javascript">
// console.log("i = ",typeof(<%=i %>));
var keep_num_true = 0;
var keep_num_false = 0;
var check = 100;

var xxxx= 0;
// console.log("xxxxxx", typeof(xxxx));
var status = <%=keep_status%>
var array = status.split(',');
var keep_num = array.length
// console.log(status);
// console.log(typeof(status));
// console.log("status length", status.length);
// console.log(array[0]);
// console.log(typeof(array[0]));
// console.log("arra length", array.length);
for (var num = 0; num < array.length; num++) {
  // console.log("array[num]",array[num]);
  if (array[num] == 'true') {
    // console.log("true--------------");
    // console.log("aaaa",num);
    keep_num_true += 1;
    // console.log("keep_num_true", keep_num_true);
  }else {
    keep_num_false += 1;
  }
}
// console.log("num",keep_num);
// console.log("num",typeof(keep_num));
// console.log("true",keep_num_true);
// console.log("true",typeof(keep_num_true));
// console.log("false",keep_num_false);
// console.log("false",typeof(keep_num_false));
  if (keep_num_true == 0) {

    var find_percent = 0;
  }else {
    // console.log("keep_num_true / keep_num * 100",(keep_num_true / keep_num));
    var find_percent = (keep_num_true / keep_num) * check;
  }
  var t1 = "<div class='progress-bar progress-bar-info' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"%'"+ ">"+"<span class='sr-only'>"+find_percent + "%"+ "Complete</span>"+find_percent + "%"+"</div>";
  // console.log("<div class='progress-bar' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"'"+ ">"+find_percent + "%"+"</div>");
  // console.log(t1);
  $('.progress').append("<div class='progress-bar progress-bar-info progress-bar-striped' role='progressbar' aria-valuenow="+"'"+find_percent+"'"+" aria-valuemin='0' aria-valuemax='100' style='width:"+find_percent+"%'"+ ">"+"<span class='sr-only'>"+find_percent + "%"+ "Complete</span>"+find_percent + "%"+"</div>")
  keep_num = 0;
  keep_num_true = 0;
  keep_num_false = 0;
  find_percent = 0;
</script>

app/views/cars/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>Editing Car</h1>
  </div>

  <br>
  <div class="container">
    <%= render 'form' %>
  </div>

</div>
<%= link_to 'Back', user_car_path(@user,@car), class: "btn btn-primary" %>

<script type="text/javascript">
  $('.checkbox-inline').addClass('checkbox-inline disabled');
  $(".inputcheckbox").attr("disabled", true);
</script>

app/views/cars/index.html.erb
<% if admin_signed_in? %>
  <%= render 'adminindex'%>
<% else %>
  <%= render 'userindex'%>
<% end %>


<!--
<label class="checkbox-inline">
  <input type="checkbox" id="inlineCheckbox1" value="option1"> 1
</label>
<label class="checkbox-inline">
  <input type="checkbox" id="inlineCheckbox2" value="option2"> 2
</label>
<label class="checkbox-inline">
  <input type="checkbox" id="inlineCheckbox3" value="option3"> 3
</label>

<div id="log"></div>
<script>
$( "input" ).on( "click", function() {
  $( "#log" ).html( $( "input:checked" ).val() + " is checked!" );
});
</script> -->

app/views/cars/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading panel-primary">
    <h1>New Car</h1>
  </div>

  <br>
  <div class="container">
    <%= render 'form' %>
  </div>

</div>
<%= link_to 'Back', user_path(@user), class: "btn btn-primary" %>