config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :cars do
        resources :car_statuses do
          resources :car_images
        end
      end
    end

  root 'users#index'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h5 class="white-text">Car Service</h5>
        <p class="grey-text text-lighten-4">This web-site is created for the customer who want to kepp track their own car that we are taking car. In order to call us, customer can see your own car through this web site.</p>
      </div>
      <div class="col-md-3 col-md-offset-6">
        <h5 class="white-text">Contacts:</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="http://boss2bmj.github.io/"><i class="fa fa-home"></i>My Blog</li>
          <li><a class="grey-text text-lighten-3" href="https://github.com/boss2bmj"><i class="fa fa-github-square"></i>GitHub</a></li>
          <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/peranat.lappakobkit"><i class="fa fa-facebook-square"></i>Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="mailto:boss2bmj@gmail.com"><i class="fa fa-envelope-o"></i>Email</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_headeradmin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%=users_path%>">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><a href= "/admin" >Dashboard</a></li>
        <li><a href="<%=users_path%>">Home</a></li>
        <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_headeruser.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%=users_path%>">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

        <li><a href= "<%=admin_session_path%>" >Sign In Admin</a></li>
        <li><a href= "<%=users_path%>" >Users</a></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <title>InternetProgrammingCarproject2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if admin_signed_in? %>
    <%= render 'layouts/headeradmin'%>
  <% else %>
    <%= render 'layouts/headeruser'%>
  <% end %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div><br><br>


  <%= render 'layouts/footer'%>

  <script>
    $(document).ready(function(){
      $('#datatable').DataTable( );
    });
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.js"></script>

  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
 <%= yield :js %>
</body>

</html>